'use strict';
const crypto=require('crypto');
const {promisify}=require('util');
const scrypt=promisify(crypto.scrypt);
function sha256(s){return crypto.createHash('sha256').update(String(s)).digest('hex')}
function rand(n=32){return crypto.randomBytes(n).toString('base64url')}
function cleanUsername(v){return String(v||'').trim().toLowerCase()}
function cleanDisplay(v){return String(v||'').replace(/[\u0000-\u001f\u007f]/g,'').trim().slice(0,24)}
function cleanEmail(v){return String(v||'').trim().toLowerCase()}
function publicUser(u){return u?{id:u.publicId,username:u.username,email:u.email||'',displayName:u.displayName,createdAt:u.createdAt}:null}
function normRecovery(v){return String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'')}
const REC_ALPHA='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
function recoveryCode(){const b=crypto.randomBytes(12);let s='';for(let i=0;i<12;i++)s+=REC_ALPHA[b[i]%REC_ALPHA.length];return s.slice(0,4)+'-'+s.slice(4,8)+'-'+s.slice(8,12)}
function recoveryHash(accountId,code){return sha256(String(accountId)+':'+normRecovery(code))}
function publicProfile(p,u,own){if(!p)return null;const out={playerId:u&&u.publicId||null,displayName:u&&u.displayName||'',bio:String(p.bio||'').slice(0,160),avatar:String(p.avatar||'default').slice(0,40),stats:{...(p.stats||{})},ranked:{TEAM:{...((p.ranked&&p.ranked.TEAM)||{})},INDIVIDUAL:{...((p.ranked&&p.ranked.INDIVIDUAL)||{})}},updatedAt:p.updatedAt||0};if(own)out.wallet={chips:Number(p.wallet&&p.wallet.chips)||0,gems:Number(p.wallet&&p.wallet.gems)||0};return out}
class IdentityService{
  constructor(store,opts={}){this.store=store;this.accessTtlMs=Math.max(300000,Number(opts.accessTtlMs||process.env.G17_ACCESS_TTL_MS||43200000));this.refreshTtlMs=Math.max(this.accessTtlMs,Number(opts.refreshTtlMs||process.env.G17_REFRESH_TTL_MS||2592000000));this.passwordMin=Math.max(8,Number(opts.passwordMin||process.env.G17_PASSWORD_MIN||10));this.dummyHash=null}
  async init(){await this.store.connect();this.dummyHash=await this._hashPassword('g17-dummy-password-'+rand(8));return true}
  async close(){return this.store.close()}
  validateUsername(v){const u=cleanUsername(v);if(!/^[a-z0-9][a-z0-9._-]{2,23}$/.test(u))return{ok:false,err:'USERNAME_INVALID'};return{ok:true,value:u}}
  validateEmail(v){const e=cleanEmail(v);if(e.length<6||e.length>160||!/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(e))return{ok:false,err:'EMAIL_INVALID'};return{ok:true,value:e}}
  async deriveUsername(email){let base=cleanEmail(email).split('@')[0].replace(/[^a-z0-9._-]+/g,'-').replace(/^[^a-z0-9]+/,'').slice(0,18);if(base.length<3)base='oyuncu';let v=base,n=0;while(await this.store.getUserByName(v)){n++;v=(base.slice(0,Math.max(3,18-String(n).length-1))+'-'+n).slice(0,24)}return v}
  validatePassword(v){v=String(v||'');if(v.length<this.passwordMin||v.length>128)return{ok:false,err:'PASSWORD_POLICY'};return{ok:true,value:v}}
  validateDisplay(v,username){const d=cleanDisplay(v||username);if(d.length<2)return{ok:false,err:'DISPLAY_NAME_INVALID'};return{ok:true,value:d}}
  async _hashPassword(password){const salt=crypto.randomBytes(16);const N=16384,r=8,p=1,key=await scrypt(String(password),salt,32,{N,r,p,maxmem:64*1024*1024});return `scrypt$${N}$${r}$${p}$${salt.toString('base64url')}$${Buffer.from(key).toString('base64url')}`}
  async _verifyPassword(password,encoded){try{const a=String(encoded||'').split('$');if(a.length!==6||a[0]!=='scrypt')return false;const N=Number(a[1]),r=Number(a[2]),p=Number(a[3]),salt=Buffer.from(a[4],'base64url'),want=Buffer.from(a[5],'base64url'),got=Buffer.from(await scrypt(String(password),salt,want.length,{N,r,p,maxmem:64*1024*1024}));return want.length===got.length&&crypto.timingSafeEqual(want,got)}catch(_){return false}}
  async rotateRecoveryCodes(accountId){const codes=Array.from({length:8},()=>recoveryCode());await this.store.setRecoveryHashes(accountId,codes.map(c=>recoveryHash(accountId,c)));return codes}
  async register(input={}){let email='';if(input.email!=null&&String(input.email).trim()){const em=this.validateEmail(input.email);if(!em.ok)return em;email=em.value;if(await this.store.getUserByEmail(email))return{ok:false,err:'EMAIL_TAKEN'}}let username='';if(input.username!=null&&String(input.username).trim()){const un=this.validateUsername(input.username);if(!un.ok)return un;username=un.value}else if(email)username=await this.deriveUsername(email);else return{ok:false,err:'USERNAME_INVALID'};const pw=this.validatePassword(input.password);if(!pw.ok)return pw;const dn=this.validateDisplay(input.displayName,username);if(!dn.ok)return dn;const t=Date.now(),u={id:crypto.randomUUID(),publicId:'p_'+rand(12),username,email,displayName:dn.value,passwordHash:await this._hashPassword(pw.value),createdAt:t,updatedAt:t,disabled:false};if(!await this.store.createUser(u))return{ok:false,err:email?'EMAIL_OR_USERNAME_TAKEN':'USERNAME_TAKEN'};const recoveryCodes=await this.rotateRecoveryCodes(u.id),sess=await this.issueSession(u.id);return{ok:true,user:publicUser(u),recoveryCodes,...sess}}
  async login(input={}){const raw=String(input.identity||input.email||input.username||'').trim(),isEmail=raw.includes('@');let u=null;if(isEmail){const em=this.validateEmail(raw);u=em.ok?await this.store.getUserByEmail(em.value):null}else{const un=this.validateUsername(raw);u=un.ok?await this.store.getUserByName(un.value):null}const encoded=u&&u.passwordHash||this.dummyHash,good=await this._verifyPassword(input.password,encoded);if(!u||!good||u.disabled)return{ok:false,err:'INVALID_CREDENTIALS'};const sanc=await this.activeSanction(u.id);if(sanc&&sanc.banUntil>Date.now())return{ok:false,err:'ACCOUNT_BANNED',banUntil:sanc.banUntil};const sess=await this.issueSession(u.id);return{ok:true,user:publicUser(u),...sess}}
  async issueSession(accountId){const access=rand(32),refresh=rand(40),sessionId=crypto.randomUUID(),t=Date.now();const accessHash=sha256(access);await this.store.putSession(accessHash,{accountId,sessionId,createdAt:t},this.accessTtlMs);await this.store.putRefresh(sha256(refresh),{accountId,sessionId,accessHash,createdAt:t},this.refreshTtlMs);return{accessToken:access,refreshToken:refresh,expiresInMs:this.accessTtlMs,refreshExpiresInMs:this.refreshTtlMs}}
  async authenticate(accessToken){if(!accessToken)return null;const s=await this.store.getSession(sha256(accessToken));if(!s)return null;const u=await this.store.getUserById(s.accountId);if(!u||u.disabled)return null;return{accountId:u.id,publicId:u.publicId,username:u.username,displayName:u.displayName,sessionId:s.sessionId,user:publicUser(u)}}
  async refresh(refreshToken){if(!refreshToken)return{ok:false,err:'INVALID_REFRESH'};const h=sha256(refreshToken),r=await this.store.getRefresh(h);if(!r)return{ok:false,err:'INVALID_REFRESH'};await this.store.deleteRefresh(h);if(r.accessHash)await this.store.deleteSession(r.accessHash);const u=await this.store.getUserById(r.accountId);if(!u||u.disabled)return{ok:false,err:'INVALID_REFRESH'};const sanc=await this.activeSanction(u.id);if(sanc&&sanc.banUntil>Date.now())return{ok:false,err:'ACCOUNT_BANNED',banUntil:sanc.banUntil};const s=await this.issueSession(u.id);return{ok:true,user:publicUser(u),...s}}
  async logout(accessToken,refreshToken){if(accessToken)await this.store.deleteSession(sha256(accessToken));if(refreshToken){const h=sha256(refreshToken),r=await this.store.getRefresh(h);if(r&&r.accessHash)await this.store.deleteSession(r.accessHash);await this.store.deleteRefresh(h)}return{ok:true}}
  async logoutAll(accountId){return this.store.revokeAccountSessions(accountId)}
  async changePassword(auth,input={}){if(!auth||!auth.accountId)return{ok:false,err:'AUTH_REQUIRED'};const pw=this.validatePassword(input.newPassword);if(!pw.ok)return pw;const u=await this.store.getUserById(auth.accountId);if(!u||!await this._verifyPassword(input.currentPassword,u.passwordHash))return{ok:false,err:'INVALID_CREDENTIALS'};u.passwordHash=await this._hashPassword(pw.value);u.updatedAt=Date.now();await this.store.updateUser(u);await this.store.revokeAccountSessions(u.id);const s=await this.issueSession(u.id);return{ok:true,user:publicUser(u),...s}}
  async recover(input={}){const raw=String(input.identity||input.email||input.username||'').trim(),pw=this.validatePassword(input.newPassword);if(!pw.ok)return{ok:false,err:'RECOVERY_INVALID'};let u=null;if(raw.includes('@')){const em=this.validateEmail(raw);if(em.ok)u=await this.store.getUserByEmail(em.value)}else{const un=this.validateUsername(raw);if(un.ok)u=await this.store.getUserByName(un.value)}if(!u)return{ok:false,err:'RECOVERY_INVALID'};const want=recoveryHash(u.id,input.recoveryCode),hashes=await this.store.getRecoveryHashes(u.id);let good=false;for(const h of hashes||[]){const a=Buffer.from(String(h)),b=Buffer.from(want);if(a.length===b.length&&crypto.timingSafeEqual(a,b)){good=true;break}}if(!good)return{ok:false,err:'RECOVERY_INVALID'};u.passwordHash=await this._hashPassword(pw.value);u.updatedAt=Date.now();await this.store.updateUser(u);await this.store.revokeAccountSessions(u.id);const recoveryCodes=await this.rotateRecoveryCodes(u.id),s=await this.issueSession(u.id);return{ok:true,user:publicUser(u),recoveryCodes,...s}}
  async activeSanction(accountId){if(!accountId)return null;const s=await this.store.getSanction(accountId);if(!s)return null;const now=Date.now(),active={...s};if(active.banUntil&&active.banUntil<=now)active.banUntil=0;if(active.muteUntil&&active.muteUntil<=now)active.muteUntil=0;return active}
  async isGameBanned(accountId){const s=await this.activeSanction(accountId);return !!(s&&s.banUntil>Date.now())}
  async isMuted(accountId){const s=await this.activeSanction(accountId);return s&&s.muteUntil>Date.now()?s:null}
  async setSanction(accountId,input={}){const u=await this.store.getUserById(accountId);if(!u)return{ok:false,err:'ACCOUNT_NOT_FOUND'};const cur=await this.store.getSanction(accountId)||{},now=Date.now(),s={accountId,banUntil:input.banUntil==null?Number(cur.banUntil||0):Math.max(0,Number(input.banUntil)||0),muteUntil:input.muteUntil==null?Number(cur.muteUntil||0):Math.max(0,Number(input.muteUntil)||0),reason:String(input.reason||cur.reason||'').slice(0,240),updatedAt:now};await this.store.setSanction(accountId,s);if(s.banUntil>now)await this.store.revokeAccountSessions(accountId);return{ok:true,sanction:s,user:publicUser(u)}}
  async clearSanction(accountId){await this.store.setSanction(accountId,null);return{ok:true}}
  async addReport(reporter,subjectAccountId,input={}){const cat=String(input.category||'OTHER').toUpperCase(),allowed=new Set(['CHEATING','HARASSMENT','SPAM','NAME','CHAT','OTHER']);if(!allowed.has(cat))return{ok:false,err:'REPORT_CATEGORY_INVALID'};if(!subjectAccountId||subjectAccountId===reporter.accountId)return{ok:false,err:'REPORT_TARGET_INVALID'};const subject=await this.store.getUserById(subjectAccountId);if(!subject)return{ok:false,err:'REPORT_TARGET_INVALID'};const r={id:'r_'+rand(12),createdAt:Date.now(),reporterAccountId:reporter.accountId,subjectAccountId,subjectPublicId:subject.publicId,category:cat,note:String(input.note||'').replace(/[\u0000-\u001f\u007f]/g,' ').trim().slice(0,500),roomId:String(input.roomId||'').toUpperCase().slice(0,20),messageId:String(input.messageId||'').slice(0,80),status:'OPEN'};await this.store.addReport(r);return{ok:true,reportId:r.id}}
  async listReports(limit){return this.store.listReports(limit)}
  async resolvePublicId(pid){return this.store.getUserByPublicId(String(pid||''))}
  async resolveIdentifier(v){v=String(v||'').trim();if(!v)return null;if(v.startsWith('p_'))return this.store.getUserByPublicId(v);const un=this.validateUsername(v);return un.ok?this.store.getUserByName(un.value):null}
  async getOwnProfile(accountId){const u=await this.store.getUserById(accountId),p=await this.store.getProfile(accountId);return u&&p?publicProfile(p,u,true):null}
  async getPublicProfileByPublicId(pid){const u=await this.store.getUserByPublicId(String(pid||''));if(!u)return null;const p=await this.store.getProfile(u.id);return publicProfile(p,u,false)}
  async updateProfile(accountId,input={}){const u=await this.store.getUserById(accountId);if(!u)return{ok:false,err:'ACCOUNT_NOT_FOUND'};const p=await this.store.getProfile(accountId);if(!p)return{ok:false,err:'PROFILE_NOT_FOUND'};if(input.bio!=null)p.bio=String(input.bio).replace(/[\u0000-\u001f\u007f]/g,' ').trim().slice(0,160);if(input.avatar!=null)p.avatar=String(input.avatar).replace(/[^A-Za-z0-9._-]/g,'').slice(0,40)||'default';await this.store.setProfile(accountId,p);return{ok:true,profile:await this.getOwnProfile(accountId)}}
  async adminWallet(identifier,input={}){const u=await this.resolveIdentifier(identifier);if(!u)return{ok:false,err:'ACCOUNT_NOT_FOUND'};const txId=String(input.txId||crypto.randomUUID()).slice(0,96),chips=Math.trunc(Number(input.chipsDelta)||0),gems=Math.trunc(Number(input.gemsDelta)||0);const r=await this.store.applyWalletDelta(u.id,txId,chips,gems,String(input.reason||'ADMIN').slice(0,160));return{...r,player:publicUser(u),txId,profile:r.profile?publicProfile(r.profile,u,true):null}}
  async recordMatch(matchId,rows,settlement){return this.store.recordMatch(matchId,rows,settlement)}
  async getSettlement(matchId){return this.store.getSettlement?this.store.getSettlement(matchId):null}
  async leaderboard(mode,limit){const rows=await this.store.listRanked(mode,limit);return(rows||[]).map((r,i)=>({rank:i+1,playerId:r.publicId,displayName:r.displayName,rating:r.rating,matches:r.matches,wins:r.wins,ties:r.ties,best:r.best}))}
  status(){return this.store.status()}
}
module.exports={IdentityService,sha256,publicUser,publicProfile,recoveryHash};
